### PR TITLE
Fix eslint errors and add i18n tags

### LINKED ISSUE #228: Use i18n text on Tooltips
Follow up from #177 and [this PR](https://github.com/WWCodeTokyo/speak-her-db/pull/221/files/df7978b84699d1b9ce3af44324f4654de9db7f6c#r580862077).

Add i18n to the "Facebook", "Twitter," etc. raw text so we can adjust the eslint warning

`<!--eslint-disable-next-line @intlify/vue-i18n/no-raw-text -->`

Note it's okay to use this exception around the `<v-icon>` tags because icons are keyed on text, and we don't want to translate it. But since the tooltips are human-readable text, we want to enable translations, and therefore we don't want to disable the warning on these lines

Here's the file where the changes should be made:
web/src/components/speaker/Links.vue

And here's the documentation for how vue i18n works: https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting

### PR DESCRIPTION
**Pull request by ann-kilzer**
Resolves #228 

Fixes some lint warnings and adds i18n tags for tooltips

### CODE REVIEW

File: web/src/components/speaker/Links.vue [hunk 1]
```diff
@@ -3,43 +3,57 @@
...
         </social-button>
       </template>
-      <span>Facebook</span>
+      <span>{{ $t('findSpeaker.links.facebook') }}</span>
     </v-tooltip>
     <v-tooltip bottom>
       <template v-slot:activator="{ on }">
         <social-button :link="website">
-          <v-icon v-on="on">web</v-icon>
+          <!--eslint-disable-next-line @intlify/vue-i18n/no-raw-text -->
```
Comment (ann-kilzer) [inline web/src/components/speaker/Links.vue:39]: We need raw text for the v-icon tag

**Review by tuttiq — APPROVED** [review]
LGTM! Thanks
