### PR TITLE
Fix Tag fetching

### LINKED ISSUE #72: Fix tags on Speaker Card

### PR DESCRIPTION
**Pull request by ann-kilzer**
Resolves #72 

Could use some help on this one figuring out the filter function.

### CODE REVIEW

File: web/src/plugins/airtable.js [hunk 1]
```diff
@@ -47,6 +47,25 @@ Airtable.install = function (Vue) {
...
   };
+
+  Vue.prototype.$speakerTopics = new Map();
+
+  Vue.prototype.$getSpeakerTopics = function (speakerID, successCallback, errorCallback) {
+    if (this.$speakerTopics.hasKey(speakerID)) {
+      // return cached response
+      successCallback(this.$speakerTopics.get(speakerID));
+    } else {
+      this.$db('Topics').select({ view: 'All', fields: ['name'], filterByFormula: "({People} = 'TODO')" }).firstPage((error, records) => {
```
Comment (ann-kilzer) [inline web/src/plugins/airtable.js:58]: I wasn't finding a contains / in operator in the filterByFormula docs. https://support.airtable.com/hc/en-us/articles/203255215-Formula-Field-Reference#array_functions

File: web/src/components/SpeakerCard.vue [hunk 2]
```diff
@@ -86,7 +80,19 @@ export default {
       }
     },
   },
+  mounted() {
+    this.$getSpeakerTopics(this.speaker.id, this.setTopics, this.setError);
+  },
```
Comment (tuttiq) [inline web/src/components/SpeakerCard.vue:85]: So, instead of fetching 1~5 topics for each speaker (and probably fetching repeated ones several times across the list), for locations I put the [fetch of all locations on the `FindSpeaker` view](https://github.com/WWCodeTokyo/speak-her-db/blob/master/web/src/views/FindSpeaker.vue#L68) and passed the in-memory list [as props to the speaker card](https://github.com/WWCodeTokyo/speak-her-db/blob/master/web/src/views/FindSpeaker.vue#L31). How about we do the same for topics?

File: web/src/components/SpeakerCard.vue [hunk 3]
```diff
@@ -86,7 +80,19 @@ export default {
...
   methods: {
+    setTopics(records) {
+      this.topics = records.map((topic) => ({
+        id: topic.id,
+        text: topic.get('name'),
+      }));
+    },
+    setError(err) {
+      this.error = err;
+    },
```
Comment (tuttiq) [inline web/src/components/SpeakerCard.vue:95]: Following the previous comment, once you have the list of topics as props here on `SpeakerCard`, then you can just lookup the speaker topic IDs on the topic list here, as a computed property (here's the [example with prefectures](https://github.com/WWCodeTokyo/speak-her-db/blob/master/web/src/components/SpeakerCard.vue#L62-L65))

File: web/src/plugins/airtable.js (hunk 1 above)
Comment (tuttiq) [reply web/src/plugins/airtable.js:58]: If you follow the approach I mentioned on the comments above, then you don't need this whole function :)

File: web/src/components/SpeakerCard.vue (hunk 2 above)
Comment (ann-kilzer) [reply web/src/components/SpeakerCard.vue:85]: And then merge them in the javascript with the foreign keys in the speaker? Sure, I could do that. Thought it might be more elegant to compose the right query from the backend, using caching like your example.

File: web/src/components/SpeakerCard.vue (hunk 3 above)
Comment (ann-kilzer) [reply web/src/components/SpeakerCard.vue:95]: Thanks for the great notes
